/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import Dao.ClienteDao;
import Dao.UsuarioDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author leonardo
 */
public class Home extends javax.swing.JFrame {
    
    private final int cod_usuario;
    private final String nome;
    private final String login;
    private final String senha;
    private final String email;
    private final String tipoUsuario;
    
    private List<String> Desenvolvedores;
    private List<String> Clientes;
    
    /**
     * Creates new form Home
     * @param cod_usuario
     * @param nome
     * @param login
     * @param senha
     * @param email
     * @param tipoUsuario
     */
    public Home(int cod_usuario, String nome, String login, String senha, String email, String tipoUsuario) {
        initComponents();
        this.cod_usuario = cod_usuario;
        this.nome = nome;
        this.login = login;
        this.senha = senha;
        this.email = email;
        this.tipoUsuario = tipoUsuario;
        switch (tipoUsuario) {
            case "Desenvolvedor":
                menCadUsuario.setEnabled(false);
                menCadAlteracao.setEnabled(false);
                menCadCliente.setEnabled(false);
                break;
            case "Consultor":
                menCadUsuario.setEnabled(false);
                menCadCliente.setEnabled(false);
                break;
            case "Gerente":
                break;
            case "Master":
                break;
            default:
                menCadUsuario.setEnabled(false);
                menCadAlteracao.setEnabled(false);
                menCadCliente.setEnabled(false);
                menManuAlteracao.setEnabled(false);
                break;
        }
        lblNomUsuario.setText("Bem Vindo " + nome + "!");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();
        lblNomUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCadastro = new javax.swing.JMenu();
        menCadUsuario = new javax.swing.JMenuItem();
        menCadAlteracao = new javax.swing.JMenuItem();
        menCadCliente = new javax.swing.JMenuItem();
        menAlteracao = new javax.swing.JMenu();
        menManuAlteracao = new javax.swing.JMenuItem();
        menOpcoes = new javax.swing.JMenu();
        menAjuda = new javax.swing.JMenuItem();
        menAltPerfil = new javax.swing.JMenuItem();
        menTrocarUsuario = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setName("frmHome"); // NOI18N
        setResizable(false);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoHome.PNG"))); // NOI18N

        lblNomUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menCadastro.setText("Cadastros");

        menCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Usuario.png"))); // NOI18N
        menCadUsuario.setText("Cadastro de Usuário");
        menCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuarioActionPerformed(evt);
            }
        });
        menCadastro.add(menCadUsuario);

        menCadAlteracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menCadAlteracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alteracao.png"))); // NOI18N
        menCadAlteracao.setText("Cadastro de Alteração");
        menCadAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadAlteracaoActionPerformed(evt);
            }
        });
        menCadastro.add(menCadAlteracao);

        menCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/customer.png"))); // NOI18N
        menCadCliente.setText("Cadastro de Cliente");
        menCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadClienteActionPerformed(evt);
            }
        });
        menCadastro.add(menCadCliente);

        jMenuBar1.add(menCadastro);

        menAlteracao.setText("Alteração");

        menManuAlteracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menManuAlteracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/manutencao.png"))); // NOI18N
        menManuAlteracao.setText("Manutenção de Alterações");
        menManuAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menManuAlteracaoActionPerformed(evt);
            }
        });
        menAlteracao.add(menManuAlteracao);

        jMenuBar1.add(menAlteracao);

        menOpcoes.setText("Opções");

        menAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/help.png"))); // NOI18N
        menAjuda.setText("Ajuda");
        menAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjudaActionPerformed(evt);
            }
        });
        menOpcoes.add(menAjuda);

        menAltPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menAltPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/profile.png"))); // NOI18N
        menAltPerfil.setText("Alterar Perfil");
        menAltPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAltPerfilActionPerformed(evt);
            }
        });
        menOpcoes.add(menAltPerfil);

        menTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        menTrocarUsuario.setText("Trocar Usuário");
        menTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menTrocarUsuarioActionPerformed(evt);
            }
        });
        menOpcoes.add(menTrocarUsuario);

        menSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close.png"))); // NOI18N
        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menOpcoes.add(menSair);

        jMenuBar1.add(menOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblImg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(lblNomUsuario)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblNomUsuario)
                .addGap(96, 96, 96)
                .addComponent(lblImg)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        mensagemSair();
    }//GEN-LAST:event_menSairActionPerformed

    private void menCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuarioActionPerformed
        CadastroUsuario cadUsuario = new CadastroUsuario();
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_menCadUsuarioActionPerformed

    private void menTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menTrocarUsuarioActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Deseja Realmente Fazer Logout?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_NO_OPTION) {
            dispose();
            Login log = new Login();
            log.setVisible(true);
        }
    }//GEN-LAST:event_menTrocarUsuarioActionPerformed

    private void menManuAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menManuAlteracaoActionPerformed
        ManutencaoAlteracao manAlter = new ManutencaoAlteracao(tipoUsuario, cod_usuario);
        manAlter.setVisible(true);
    }//GEN-LAST:event_menManuAlteracaoActionPerformed

    private void menCadAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadAlteracaoActionPerformed
        try {
            BuscaDesenvolvedores();
            BuscaClientes();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] arrayDesenvolvedores = Desenvolvedores.toArray(new String[0]);
        String[] arrayClientes = Clientes.toArray(new String[0]);
        CadastroAlteracao cadAlteracao = new CadastroAlteracao(arrayDesenvolvedores, arrayClientes, tipoUsuario);
        cadAlteracao.setVisible(true);
    }//GEN-LAST:event_menCadAlteracaoActionPerformed

    private void menAltPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAltPerfilActionPerformed
        AlteraPerfil altPerfil = new AlteraPerfil(cod_usuario, nome, login, senha, email);
        altPerfil.setVisible(true);
    }//GEN-LAST:event_menAltPerfilActionPerformed

    private void menAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjudaActionPerformed
        JOptionPane.showMessageDialog(null, "O Mais Avançado Sistema de Alterações, Qualquer Dúvida: Ligue para 0800-40625");
    }//GEN-LAST:event_menAjudaActionPerformed

    private void menCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadClienteActionPerformed
        CadastroCliente cadCliente = new CadastroCliente();
        cadCliente.setVisible(true);
    }//GEN-LAST:event_menCadClienteActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }
    
    public void BuscaDesenvolvedores () throws SQLException {
        UsuarioDao dao = new UsuarioDao();
        Desenvolvedores = dao.buscaUsuarios("Desenvolvedor");
    }
    
    public void BuscaClientes () throws SQLException {
        ClienteDao dao = new ClienteDao();
        Clientes = dao.buscaClientes();
    }
    
    // Exibe Mensagem de Confirmação de Saida.
    private void mensagemSair() {
        int resp = JOptionPane.showConfirmDialog(this, "Deseja Realmente Sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(resp == JOptionPane.YES_NO_OPTION) {
            dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNomUsuario;
    private javax.swing.JMenuItem menAjuda;
    private javax.swing.JMenuItem menAltPerfil;
    private javax.swing.JMenu menAlteracao;
    private javax.swing.JMenuItem menCadAlteracao;
    private javax.swing.JMenuItem menCadCliente;
    private javax.swing.JMenuItem menCadUsuario;
    private javax.swing.JMenu menCadastro;
    private javax.swing.JMenuItem menManuAlteracao;
    private javax.swing.JMenu menOpcoes;
    private javax.swing.JMenuItem menSair;
    private javax.swing.JMenuItem menTrocarUsuario;
    // End of variables declaration//GEN-END:variables
}